language: java
jdk:
  - openjdk11

# 1
branches:
  only:
    - master

# Travis CI 서버의 Home
# 2
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# 3
script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
# 4
notifications:
  email:
    recipients:
      - ultra16@naver.com
