language: java
jdk:
  - openjdk11

# 1
branches:
  only:
    - master

# Travis CI 서버의 Home
# 2
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# 3
script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
# 4
notifications:
  email:
    recipients:
      - ultra16@naver.com


before_deploy: # (1)
  - zip -r survey-deploy * # (2)
  - mkdir -p deploy # (3)
  - mv survey-deploy.zip deploy/survey-deploy.zip # (4)

deploy: # (5)
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting에 설정된 값
    bucket: survey-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리 # (6)
    wait-until-deployed: true