language: java
jdk:
  - openjdk11

# 1
branches:
  only:
    - master

# Travis CI 서버의 Home
# 2
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# 3
script: "./gradlew clean build"

before_deploy: # (1)
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/survey-deploy.zip

deploy: # (5)
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting에 설정된 값
    bucket: survey-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리 # (6)
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: survey-build # S3 버킷
    key: survey-deploy.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: survey # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: survey-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
# 4
notifications:
  email:
    recipients:
      - ultra16@naver.com